import {AntdRegistry} from "@ant-design/nextjs-registry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 const AppLayout =  ({ children }) => {
  return (
    <html lang="en">
      <body>
      <AntdRegistry>
        {children}
      </AntdRegistry>
      </body>
    </html>
  );
}


export default AppLayout